In [1]:
from first_moments import*
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from numpy import*
from matplotlib.pyplot import*

In [2]:
mean1 = np.array([ 0.14363514, -0.14012427, -0.15129467, -0.08996013,-0.08996013,-0.08996013,\
                  0.,          0.,  2.04589091,  0., 0., 0., \
                  3.57029504,  0.,          0.,          2.60634211,2.60634211,2.60634211, \
                  0.09731858,  0.])

In [3]:
mean2 = np.array([ 0.17767041, -0.37634992, -0.1206068,  -0.12730992,-0.12730992,-0.12730992, \
                  0.,          0.77369741,   0.84825043,  0.,0.,0.,\
                  2.70967305,  0.,          0.,          1.58986934,1.58986934,1.58986934,\
  0.09348547,  0.        ])

In [4]:
mean3 = np.array([ 0.13020397, 0.13020397, -0.2625163,-0.17407299,-0.17407299, -0.1496972,\
                   2.83826223,  2.83826223,2.16380442, 0.,     0.,    0.,    \
                  10.58012192,10.58012192,0.,0.,0.,  1.54487166 ,\
                    0.11620619,  0.        ])

In [5]:
fst = cr_sec()
zs = linspace(0.25,0.95,100)
qq=10.58
fst.mass=1.115

In [6]:
fst1_moms = array([])
fst1_moms1 = array([])
fst1_moms2 = array([])
fst1_moms3 = array([])
fst1_moms4 = array([])
fst1_moms5 = array([])
zlcs = array([])

for z1 in zs:
    fst1_moms= np.append(fst1_moms,fst.cross_sec2_polda_jk('lbd',z1,qq,mean1)[0])
    #fst.cross_sec2_polda('lbd',z1,qq,mean)
    fst1_moms1= np.append(fst1_moms1,fst.cross_sec2_polda_jk('lbd',z1,qq,mean1)[1])
    fst1_moms2= np.append(fst1_moms2,fst.cross_sec2_polda_jk('lbd',z1,qq,mean1)[2])
    fst1_moms3= np.append(fst1_moms3,fst.cross_sec2_polda_jk('lbd',z1,qq,mean1)[3])
    fst1_moms4= np.append(fst1_moms4,fst.cross_sec2_polda_jk('lbd',z1,qq,mean1)[4])
    fst1_moms5= np.append(fst1_moms5,fst.cross_sec2_polda_jk('lbd',z1,qq,mean1)[5])
    zlcs= np.append(zlcs,fst.jack(z1)[1])

In [7]:
fst2_moms = array([])
fst2_moms1 = array([])
fst2_moms2 = array([])
fst2_moms3 = array([])
fst2_moms4 = array([])
fst2_moms5 = array([])
zlcs = array([])

for z1 in zs:
    fst2_moms= np.append(fst2_moms,fst.cross_sec2_polda_jk('lbd',z1,qq,mean2)[0])
    #fst.cross_sec2_polda('lbd',z1,qq,mean)
    fst2_moms1= np.append(fst2_moms1,fst.cross_sec2_polda_jk('lbd',z1,qq,mean2)[1])
    fst2_moms2= np.append(fst2_moms2,fst.cross_sec2_polda_jk('lbd',z1,qq,mean2)[2])
    fst2_moms3= np.append(fst2_moms3,fst.cross_sec2_polda_jk('lbd',z1,qq,mean2)[3])
    fst2_moms4= np.append(fst2_moms4,fst.cross_sec2_polda_jk('lbd',z1,qq,mean2)[4])
    fst2_moms5= np.append(fst2_moms5,fst.cross_sec2_polda_jk('lbd',z1,qq,mean2)[5])
    zlcs= np.append(zlcs,fst.jack(z1)[1])

In [8]:
fst3_moms = array([])
fst3_moms1 = array([])
fst3_moms2 = array([])
fst3_moms3 = array([])
fst3_moms4 = array([])
fst3_moms5 = array([])
zlcs = array([])

for z1 in zs:
    fst3_moms= np.append(fst3_moms,fst.cross_sec2_polda_jk('lbd',z1,qq,mean3)[0])
    #fst.cross_sec2_polda('lbd',z1,qq,mean)
    fst3_moms1= np.append(fst3_moms1,fst.cross_sec2_polda_jk('lbd',z1,qq,mean3)[1])
    fst3_moms2= np.append(fst3_moms2,fst.cross_sec2_polda_jk('lbd',z1,qq,mean3)[2])
    fst3_moms3= np.append(fst3_moms3,fst.cross_sec2_polda_jk('lbd',z1,qq,mean3)[3])
    fst3_moms4= np.append(fst3_moms4,fst.cross_sec2_polda_jk('lbd',z1,qq,mean3)[4])
    fst3_moms5= np.append(fst3_moms5,fst.cross_sec2_polda_jk('lbd',z1,qq,mean3)[5])
    zlcs= np.append(zlcs,fst.jack(z1)[1])

In [9]:
df1 = pd.read_csv('fit_parameters/new_gauss_su_charm_no_no_def.csv')
df2 = pd.read_csv('fit_parameters/new_gauss_su_charm_no_yes_def.csv')
df3 = pd.read_csv('fit_parameters/new_gauss_su_charm_yes_yes_def.csv')

In [10]:
up_min= array([])
do_min = array([])
st_min = array([])

upb_min = array([])
dob_min = array([])
stb_min = array([])

up_max= array([])
do_max = array([])
st_max = array([])

upb_max = array([])
dob_max = array([])
stb_max = array([])


for z1 in zs:
    up_tmp = array([])
    do_tmp = array([])
    st_tmp = array([])

    upb_tmp = array([])
    dob_tmp = array([])
    stb_tmp = array([])
    for nup, ndo, nst, nsea, ast, bup, bsea in zip(df1.NUP,df1.NDO,df1.NST,df1.NSEA,df1.AST,df1.BUP,df1.BSEA):

        f_prm=arange(0.,18.,1.)
        f_prm[0] = nup
        f_prm[1] = ndo#par[0]  #do
        f_prm[2] = nst  #par[0]      #st
        f_prm[3] = nsea  #par[0]      #upb
        f_prm[4] = f_prm[3] #par[0]      #dob
        f_prm[5] = f_prm[3] # par[0]      #stb
        #¯¯¯¯¯¯
        f_prm[6] = 0 #par[0]      #aup
        f_prm[7] = 0 #par[0]      #ado
        f_prm[8] = ast  # par[0]      #ast
        f_prm[9] = 0# par[0]      #aupb
        f_prm[10] = f_prm[9] #par[0]      #adob
        f_prm[11] = f_prm[9] #par[0]      #astb
        #¯#¯¯¯¯¯¯¯
        f_prm[12] = bup #par[0]      #bup
        f_prm[13] = 0 #par[0]      #bdo
        f_prm[14] = 0# par[0]      #bst
        f_prm[15] = bsea #par[0]      #bupb
        f_prm[16] = f_prm[15] #par[0]      #bdob
        f_prm[17] = f_prm[15] # par[0]      #bstb
        #print(pt_pp)
        #print(nup)
        #print(fst.cross_sec2_polda('lbd',z1,qq,f_prm)[0])
        up_tmp = np.append(up_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[0])
        do_tmp = np.append(do_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[1])
        st_tmp = np.append(st_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[2])

        upb_tmp = np.append(upb_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[3])
        dob_tmp = np.append(dob_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[4])
        stb_tmp = np.append(stb_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[5])
        
    up_min= np.append(up_min,min(up_tmp))
    do_min = np.append(do_min,min(do_tmp))
    st_min = np.append(st_min,min(st_tmp))

    upb_min = np.append(upb_min,min(upb_tmp))
    dob_min = np.append(dob_min,min(dob_tmp))
    stb_min = np.append(stb_min,min(stb_tmp))

    up_max= np.append(up_max,max(up_tmp))
    do_max = np.append(do_max,max(do_tmp))
    st_max = np.append(st_max,max(st_tmp))

    upb_max = np.append(upb_max,max(upb_tmp))
    dob_max = np.append(dob_max,max(dob_tmp))
    stb_max = np.append(stb_max,max(stb_tmp))
df1

,NUP,NDO,NST,NSEA,AST,BUP,BSEA,PP2,chi
0,0.185447,-0.141136,-0.182721,-0.103286,2.417908,3.875562,2.135000,0.121994,116.179406
1,0.161755,-0.157542,-0.172319,-0.112372,2.257670,3.511622,2.962888,0.118032,106.995550
2,0.164622,-0.147470,-0.203524,-0.132684,2.519056,3.315955,3.385634,0.113679,116.262987
3,0.173043,-0.143832,-0.143182,-0.104460,1.884702,4.146597,2.951389,0.104993,105.274017
4,0.203239,-0.168082,-0.121230,-0.140561,1.797557,4.148582,3.660050,0.128643,108.944103
...,...,...,...,...,...,...,...,...,...
1077,0.189536,-0.162161,-0.187116,-0.129086,2.417533,3.960787,3.299830,0.122051,107.649668
1078,0.129872,-0.139467,-0.117235,-0.090713,1.720626,3.311715,2.879163,0.101297,109.940547
1079,0.174655,-0.149607,-0.149382,-0.127230,2.152773,3.832652,3.371708,0.122122,111.755989
1080,0.126109,-0.155201,-0.164783,-0.100737,2.190233,3.091212,3.036658,0.101114,111.295790
1081,0.199272,-0.161221,-0.151201,-0.122741,1.905403,4.219614,3.378872,0.109020,110.861860

In [11]:
a =pd.DataFrame([])

a['UP'] = fst1_moms
a['DO'] = fst1_moms1
a['ST'] = fst1_moms2
a['UPb'] = fst1_moms3
a['DOb'] = fst1_moms4
a['STb'] = fst1_moms5
a['UP_min'] = up_min
a['DO_min'] = do_min
a['ST_min'] = st_min
a['UPb_min'] = upb_min
a['DOb_min'] = dob_min
a['STb_min'] = stb_min

a['UP_max'] = up_max
a['DO_max'] = do_max
a['ST_max'] = st_max
a['UPb_max'] = upb_max
a['DOb_max'] = dob_max
a['STb_max'] = stb_max

a['zs']=zlcs
a.to_csv('first_moments_2h_1scenario.csv')

In [12]:
df2

,NUP,NDO,NST,NSEA,ADO,AST,BUP,BSEA,PP2,chi
0,0.141186,-0.726498,-0.089631,-0.124346,1.737929,0.486392,2.266063,1.504214,0.086941,125.211843
1,0.156285,-0.609225,-0.125244,-0.122086,1.480349,0.971113,2.741265,1.593948,0.074462,114.969733
2,0.135057,-0.430149,-0.122718,-0.094274,0.765985,0.804618,2.363037,1.618307,0.078389,114.754028
3,0.112583,-0.380746,-0.124107,-0.084427,0.902522,1.006733,1.845183,0.909789,0.068044,114.294809
4,0.180082,-0.653440,-0.134515,-0.149228,1.549144,1.207671,3.108525,2.173218,0.073407,126.676029
...,...,...,...,...,...,...,...,...,...,...
837,0.207421,-0.601280,-0.120253,-0.170344,1.345714,0.893144,2.867262,2.222910,0.106135,123.269792
838,0.209245,-0.322504,-0.142492,-0.150449,0.784331,1.177431,2.954808,1.646560,0.099978,113.700164
839,0.191665,-0.451870,-0.134409,-0.133842,0.846529,1.003124,2.734428,1.555029,0.098114,112.603710
840,0.235534,-0.165670,-0.122616,-0.148642,0.151130,0.945140,3.465806,1.831115,0.100820,117.141578
841,0.187488,-0.384657,-0.125335,-0.135961,0.855795,0.899922,3.052468,1.883219,0.083999,113.067990

In [13]:
up_min= array([])
do_min = array([])
st_min = array([])

upb_min = array([])
dob_min = array([])
stb_min = array([])

up_max= array([])
do_max = array([])
st_max = array([])

upb_max = array([])
dob_max = array([])
stb_max = array([])


for z1 in zs:
    up_tmp = array([])
    do_tmp = array([])
    st_tmp = array([])

    upb_tmp = array([])
    dob_tmp = array([])
    stb_tmp = array([])
    for nup, ndo, nst, nsea, ado, ast, bup, bsea in zip(df2.NUP,df2.NDO,df2.NST,df2.NSEA,df2.ADO,df2.AST,df2.BUP,df2.BSEA):

        f_prm=arange(0.,18.,1.)
        f_prm[0] = nup
        f_prm[1] = ndo#par[0]  #do
        f_prm[2] = nst  #par[0]      #st
        f_prm[3] = nsea  #par[0]      #upb
        f_prm[4] = f_prm[3] #par[0]      #dob
        f_prm[5] = f_prm[3] # par[0]      #stb
        #¯¯¯¯¯¯
        f_prm[6] = 0 #par[0]      #aup
        f_prm[7] = ado #par[0]      #ado
        f_prm[8] = ast  # par[0]      #ast
        f_prm[9] = 0# par[0]      #aupb
        f_prm[10] = f_prm[9] #par[0]      #adob
        f_prm[11] = f_prm[9] #par[0]      #astb
        #¯#¯¯¯¯¯¯¯
        f_prm[12] = bup #par[0]      #bup
        f_prm[13] = 0 #par[0]      #bdo
        f_prm[14] = 0# par[0]      #bst
        f_prm[15] = bsea #par[0]      #bupb
        f_prm[16] = f_prm[15] #par[0]      #bdob
        f_prm[17] = f_prm[15] # par[0]      #bstb
        #print(pt_pp)
        #print(nup)
        #print(fst.cross_sec2_polda('lbd',z1,qq,f_prm)[0])
        up_tmp = np.append(up_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[0])
        do_tmp = np.append(do_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[1])
        st_tmp = np.append(st_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[2])

        upb_tmp = np.append(upb_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[3])
        dob_tmp = np.append(dob_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[4])
        stb_tmp = np.append(stb_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[5])
        
    up_min= np.append(up_min,min(up_tmp))
    do_min = np.append(do_min,min(do_tmp))
    st_min = np.append(st_min,min(st_tmp))

    upb_min = np.append(upb_min,min(upb_tmp))
    dob_min = np.append(dob_min,min(dob_tmp))
    stb_min = np.append(stb_min,min(stb_tmp))

    up_max= np.append(up_max,max(up_tmp))
    do_max = np.append(do_max,max(do_tmp))
    st_max = np.append(st_max,max(st_tmp))

    upb_max = np.append(upb_max,max(upb_tmp))
    dob_max = np.append(dob_max,max(dob_tmp))
    stb_max = np.append(stb_max,max(stb_tmp))
df2

,NUP,NDO,NST,NSEA,ADO,AST,BUP,BSEA,PP2,chi
0,0.141186,-0.726498,-0.089631,-0.124346,1.737929,0.486392,2.266063,1.504214,0.086941,125.211843
1,0.156285,-0.609225,-0.125244,-0.122086,1.480349,0.971113,2.741265,1.593948,0.074462,114.969733
2,0.135057,-0.430149,-0.122718,-0.094274,0.765985,0.804618,2.363037,1.618307,0.078389,114.754028
3,0.112583,-0.380746,-0.124107,-0.084427,0.902522,1.006733,1.845183,0.909789,0.068044,114.294809
4,0.180082,-0.653440,-0.134515,-0.149228,1.549144,1.207671,3.108525,2.173218,0.073407,126.676029
...,...,...,...,...,...,...,...,...,...,...
837,0.207421,-0.601280,-0.120253,-0.170344,1.345714,0.893144,2.867262,2.222910,0.106135,123.269792
838,0.209245,-0.322504,-0.142492,-0.150449,0.784331,1.177431,2.954808,1.646560,0.099978,113.700164
839,0.191665,-0.451870,-0.134409,-0.133842,0.846529,1.003124,2.734428,1.555029,0.098114,112.603710
840,0.235534,-0.165670,-0.122616,-0.148642,0.151130,0.945140,3.465806,1.831115,0.100820,117.141578
841,0.187488,-0.384657,-0.125335,-0.135961,0.855795,0.899922,3.052468,1.883219,0.083999,113.067990

In [14]:
a =pd.DataFrame([])

a['UP'] = fst2_moms
a['DO'] = fst2_moms1
a['ST'] = fst2_moms2
a['UPb'] = fst2_moms3
a['DOb'] = fst2_moms4
a['STb'] = fst2_moms5
a['UP_min'] = up_min
a['DO_min'] = do_min
a['ST_min'] = st_min
a['UPb_min'] = upb_min
a['DOb_min'] = dob_min
a['STb_min'] = stb_min

a['UP_max'] = up_max
a['DO_max'] = do_max
a['ST_max'] = st_max
a['UPb_max'] = upb_max
a['DOb_max'] = dob_max
a['STb_max'] = stb_max

a['zs']=zlcs
a.to_csv('first_moments_2h_2scenario.csv')

In [15]:
df3

,NUP,NDO,NST,NSEA,AUP,AST,BUP,BDO,PP2,chi
0,0.152862,-0.155404,-0.372957,-0.208682,3.258904,2.917543,11.054183,1.473164,0.141155,133.200343
1,0.130288,-0.157071,-0.331236,-0.176582,2.722649,2.650980,10.184791,1.777626,0.112712,122.468982
2,0.143971,-0.141624,-0.299316,-0.180737,6.873996,2.433486,22.658673,1.401903,0.121458,133.199436
3,0.125945,-0.123623,-0.265371,-0.164902,3.020636,2.264351,11.163992,1.329939,0.109470,121.906408
4,0.135132,-0.162558,-0.293509,-0.168382,3.729678,2.437390,13.554371,1.584839,0.106347,123.134256
...,...,...,...,...,...,...,...,...,...,...
1246,0.139775,-0.162260,-0.329742,-0.184844,2.209952,2.568629,8.703452,1.411524,0.125563,121.555079
1247,0.129600,-0.169917,-0.261230,-0.168327,2.503337,2.119942,10.051726,1.760491,0.112173,121.093138
1248,0.121368,-0.134923,-0.301007,-0.163147,2.771762,2.223676,10.576494,1.650505,0.107176,121.499824
1249,0.112661,-0.157475,-0.185145,-0.151055,2.246709,1.558026,8.992639,1.675798,0.093611,132.085996
1250,0.130697,-0.155336,-0.245633,-0.174926,2.404997,2.152213,9.312888,1.589912,0.109441,121.985859

In [16]:
up_min= array([])
do_min = array([])
st_min = array([])

upb_min = array([])
dob_min = array([])
stb_min = array([])

up_max= array([])
do_max = array([])
st_max = array([])

upb_max = array([])
dob_max = array([])
stb_max = array([])


for z1 in zs:
    up_tmp = array([])
    do_tmp = array([])
    st_tmp = array([])

    upb_tmp = array([])
    dob_tmp = array([])
    stb_tmp = array([])
    for nup, ndo, nst, nsea,aup, ast, bup,bdo in zip(df3.NUP,df3.NDO,df3.NST,df3.NSEA,df3.AUP,df3.AST,df3.BUP,df3.BDO):

        f_prm=arange(0.,18.,1.)
        f_prm[0] = nup
        f_prm[1] = nup#par[0]  #do
        f_prm[2] = nst  #par[0]      #st
        f_prm[3] = nsea  #par[0]      #upb
        f_prm[4] = nsea #par[0]      #dob
        f_prm[5] = ndo # par[0]      #stb
        #¯¯¯¯¯¯
        f_prm[6] = aup #par[0]      #aup
        f_prm[7] = aup #par[0]      #ado
        f_prm[8] = ast  # par[0]      #ast
        f_prm[9] = 0# par[0]      #aupb
        f_prm[10] = f_prm[9] #par[0]      #adob
        f_prm[11] = f_prm[9] #par[0]      #astb
        #¯#¯¯¯¯¯¯¯
        f_prm[12] = bup #par[0]      #bup
        f_prm[13] = bup #par[0]      #bdo
        f_prm[14] = 0# par[0]      #bst
        f_prm[15] =  0#par[0]      #bupb
        f_prm[16] =  0#par[0]      #bdob
        f_prm[17] = bdo # par[0]      #bstb
        #print(pt_pp)
        #print(nup)
        #print(fst.cross_sec2_polda('lbd',z1,qq,f_prm)[0])
        up_tmp = np.append(up_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[0])
        do_tmp = np.append(do_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[1])
        st_tmp = np.append(st_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[2])

        upb_tmp = np.append(upb_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[3])
        dob_tmp = np.append(dob_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[4])
        stb_tmp = np.append(stb_tmp,fst.cross_sec2_polda_jk('lbd',z1,qq,f_prm)[5])
        
    up_min= np.append(up_min,min(up_tmp))
    do_min = np.append(do_min,min(do_tmp))
    st_min = np.append(st_min,min(st_tmp))

    upb_min = np.append(upb_min,min(upb_tmp))
    dob_min = np.append(dob_min,min(dob_tmp))
    stb_min = np.append(stb_min,min(stb_tmp))

    up_max= np.append(up_max,max(up_tmp))
    do_max = np.append(do_max,max(do_tmp))
    st_max = np.append(st_max,max(st_tmp))

    upb_max = np.append(upb_max,max(upb_tmp))
    dob_max = np.append(dob_max,max(dob_tmp))
    stb_max = np.append(stb_max,max(stb_tmp))
df2

,NUP,NDO,NST,NSEA,ADO,AST,BUP,BSEA,PP2,chi
0,0.141186,-0.726498,-0.089631,-0.124346,1.737929,0.486392,2.266063,1.504214,0.086941,125.211843
1,0.156285,-0.609225,-0.125244,-0.122086,1.480349,0.971113,2.741265,1.593948,0.074462,114.969733
2,0.135057,-0.430149,-0.122718,-0.094274,0.765985,0.804618,2.363037,1.618307,0.078389,114.754028
3,0.112583,-0.380746,-0.124107,-0.084427,0.902522,1.006733,1.845183,0.909789,0.068044,114.294809
4,0.180082,-0.653440,-0.134515,-0.149228,1.549144,1.207671,3.108525,2.173218,0.073407,126.676029
...,...,...,...,...,...,...,...,...,...,...
837,0.207421,-0.601280,-0.120253,-0.170344,1.345714,0.893144,2.867262,2.222910,0.106135,123.269792
838,0.209245,-0.322504,-0.142492,-0.150449,0.784331,1.177431,2.954808,1.646560,0.099978,113.700164
839,0.191665,-0.451870,-0.134409,-0.133842,0.846529,1.003124,2.734428,1.555029,0.098114,112.603710
840,0.235534,-0.165670,-0.122616,-0.148642,0.151130,0.945140,3.465806,1.831115,0.100820,117.141578
841,0.187488,-0.384657,-0.125335,-0.135961,0.855795,0.899922,3.052468,1.883219,0.083999,113.067990

In [17]:
a =pd.DataFrame([])

a['UP'] = fst3_moms
a['DO'] = fst3_moms1
a['ST'] = fst3_moms2
a['UPb'] = fst3_moms3
a['DOb'] = fst3_moms4
a['STb'] = fst3_moms5
a['UP_min'] = up_min
a['DO_min'] = do_min
a['ST_min'] = st_min
a['UPb_min'] = upb_min
a['DOb_min'] = dob_min
a['STb_min'] = stb_min

a['UP_max'] = up_max
a['DO_max'] = do_max
a['ST_max'] = st_max
a['UPb_max'] = upb_max
a['DOb_max'] = dob_max
a['STb_max'] = stb_max

a['zs']=zlcs
a.to_csv('first_moments_2h_3scenario.csv')